/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJni */

#ifndef _Included_TestJni
#define _Included_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJni
 * Method:    linux_main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TestJni_linux_1main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
